on:
  push:
    branches-ignore:
      - main
jobs:
  single-test-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - run: poetry install -vvv --no-interaction
      - run: poetry run pytest
